name: Publish to Snap Store

env:
  RELEASE: edge

on:
  push:
    branches:
      - '2/edge'
  workflow_call:

jobs:
  ci-tests:
    name: Build and Run Tests
    uses: ./.github/workflows/ci.yaml

  publish:
    name: publish
    runs-on: ubuntu-latest
    timeout-minutes: 15
    needs:
      - ci-tests
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install required dependencies
        run: |
          sudo snap install yq

      - name: Download snap file
        uses: actions/download-artifact@v4
        with:
          name: opensearch_snap_amd64
          path: .

      - name: Set snap release channel
        run: |
          version="$(cat snap/snapcraft.yaml | yq .version)"
          channel="${version%%.*}/${{env.RELEASE}}"
          
          echo "version=${version}" >> $GITHUB_ENV
          echo "channel=${channel}" >> $GITHUB_ENV

      - name: Publish snap to Store
        id: publish
        uses: snapcore/action-publish@v1
        env:
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.STORE_LOGIN }}
        with:
          snap: opensearch_${{env.version}}_amd64.snap
          release: ${{env.channel}}

      - name: Upload snapcraft logs
        if: ${{ failure() && steps.publish.outcome == 'failure' }}
        uses: actions/upload-artifact@v3
        with:
          name: snapcraft-release-logs
          path: ~/.local/state/snapcraft/log/
          if-no-files-found: error
